services:
  - type: web
    name: discord-delete-bot
    env: python
    pythonVersion: 3.12.3
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: PORT
        value: 10000
